# -*- coding: utf-8 -*-
"""Anveshaka

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oiajOfrUHgkfG_JtS_EFK8zTqeRTNsEk
"""

# ============================================
# 🪔 ANVESHAKA — Kerala Storyteller Edition (Base Draft 4.2 + Streamlit Cloud Ready)
# ============================================

import streamlit as st
import os, textwrap, requests
from pathlib import Path
from gtts import gTTS

# ---------- Helper Functions ----------
def show_media(url: str, caption: str = ''):
    """Show image or video depending on URL."""
    if 'youtu' in url:
        st.video(url)
        return
    try:
        r = requests.get(url, timeout=8)
        if r.ok and 'image' in r.headers.get('Content-Type', ''):
            st.image(url, use_container_width=True, caption=caption)
        else:
            raise RuntimeError('Invalid media link')
    except Exception:
        st.image(
            'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Oil_lamp_India.svg/256px-Oil_lamp_India.svg.png',
            width=120, caption='(Image unavailable – placeholder used)'
        )
        st.write('🔗 Media link:', url)

def narrate(text: str):
    """Generate and play narration audio."""
    try:
        tts = gTTS(text=text, lang='en')
        tts.save('chechi_voice.mp3')
        st.audio('chechi_voice.mp3')
    except Exception as e:
        st.warning(f'Could not synthesize audio: {e}')

# ---------- Page Config + Style ----------
st.set_page_config(page_title='Anveshaka', page_icon='🪔', layout='centered')

st.markdown('''
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;700&family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
html, body, [data-testid="stAppViewContainer"] {
  background: linear-gradient(180deg, #fdfaf7 0%, #f5ebe0 100%) !important;
  color: #4b3b2b;
  font-family: 'Poppins', sans-serif;
}
h1, h2, h3, h4, h5 {
  font-family: 'Playfair Display', serif !important;
  color: #3b2f2f !important;
}
h1 { font-size: 46px !important; }
h2 { font-size: 34px !important; }
p, div, span, li {
  font-size: 18px !important;
  line-height: 1.7;
}
strong, b { color: #d97706 !important; }
.stButton>button {
  background: linear-gradient(90deg, #3b2f2f, #5a4636) !important;
  color: #fdfaf7 !important;
  border-radius: 8px !important;
  font-weight: 600 !important;
}
.stSelectbox label, .stRadio label, .stMarkdown li, .stMarkdown p {
  color: #3b2f2f !important;
  opacity: 1 !important;
}
[data-testid="stRadio"] div[role="radiogroup"] label p,
[data-testid="stRadio"] div[role="radiogroup"] label span,
[data-testid="stRadio"] div[role="radiogroup"] label div {
  color: #3b2f2f !important;
  opacity: 1 !important;
  font-weight: 500 !important;
  font-size: 18px !important;
}
</style>
''', unsafe_allow_html=True)

# ---------- Header ----------
st.markdown(
    "<h1 style='text-align:center;'>🪔 Anveshaka</h1>"
    "<h3 style='text-align:center;'>The Explorer of India’s Science & Culture</h3>",
    unsafe_allow_html=True
)

st.write(
    "**Anveshaka** is your digital storyteller — blending **ritual, rhythm, and reason**. "
    "It connects India’s living traditions to hidden layers of **science, ecology, and human psychology.**"
)

st.markdown('---')

# ---------- State Selection ----------
st.subheader('🌍 Choose Your State:')
state = st.selectbox(
    '',
    [
        'Select an Indian State',
        'Kerala (Active Demo)',
        'Maharashtra (Coming Soon)',
        'Tamil Nadu (Coming Soon)',
        'West Bengal (Coming Soon)',
        '...More States Coming Soon'
    ]
)

# ---------- Kerala Section ----------
if state == 'Kerala (Active Demo)':
    st.markdown("## 🏝️ Welcome to Kerala – God’s Own Country")

    st.image(
        'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Oil_lamp_India.svg/256px-Oil_lamp_India.svg.png',
        caption='Chechi – Your Kerala Storyteller', width=120
    )

    st.info(textwrap.dedent('''
    👋 Namaskaram! I’m **Chechi**, your storyteller from Kerala.
    Let’s explore five living traditions — each carrying rhythm, color, devotion, and science.
    '''))

    st.markdown('### 🎬 Kerala — State Intro')
    st.video('https://www.youtube.com/watch?v=FEDpW292UKA')

    st.markdown('---')
    st.subheader('🎭 Explore Kerala’s Living Traditions')

    # ---------- Rituals ----------
    rituals = {
        'Theyyam — When Humans Become Gods': {
            'media': 'https://youtu.be/0VSVAt0B_Ho',
            'story': textwrap.dedent('''
            In the misty groves of North Kerala, as dawn breaks, the sound of chenda drums rises like thunder.
            From behind a curtain of smoke and vermilion, a man emerges — his face painted in blazing red,
            his body wrapped in palm leaves, his eyes reflecting divinity. This is **Theyyam**, where the human becomes god.
            '''),
            'history': 'Theyyam dates back nearly 1,500 years to pre-Aryan tribal practices.',
            'science': [
                '🧠 **Sound entrainment** – rhythmic drumming shifts brainwaves and induces trance.',
                '🎨 **Natural pigments** – antiseptic and cooling.',
                '🌿 **Sacred groves** – preserve biodiversity.'
            ],
            'genz': 'If you could embody any power during a Theyyam dance — focus 🧘, endurance 💪, or creativity 🎭 — what would it be?'
        },
        'Onam — The Festival of a King Who Never Left': {
            'media': 'https://youtu.be/gHESEeS1kGk',
            'story': 'Onam is the scent of banana leaves, marigolds, and songs of unity...',
            'history': 'Onam grew from agrarian harvest rituals and the legend of Mahabali’s yearly visit.',
            'science': [
                '🌾 **Seasonal synchrony** – harvest timing.',
                '🌸 **Fractal geometry** – in floral patterns.',
                '🚣 **Hydrodynamics** – snake boats minimize drag.'
            ],
            'genz': 'Imagine your crew in a boat race — are you the rower ⚓, beat caller 🥁, or designer 🎨?'
        }
    }

    ritual_options = ['Select a Ritual'] + list(rituals.keys())
    ritual = st.selectbox('Choose a Ritual to Explore', ritual_options)

    if ritual != 'Select a Ritual':
        R = rituals[ritual]
        show_media(R['media'], caption=ritual)
        st.markdown(f"## {ritual}")
        st.markdown(f"<p style='text-align:justify;'>{R['story']}</p>", unsafe_allow_html=True)
        st.caption(f"📜 **Historical Insight:** {R['history']}")

        st.markdown('---')
        st.subheader("🤔 Before We Dive Deeper...")
        st.write("How do you think these performers achieve such transformations?")

        if 'show_science' not in st.session_state: st.session_state.show_science = False
        if 'show_quiz' not in st.session_state: st.session_state.show_quiz = False
        if 'quiz_step' not in st.session_state: st.session_state.quiz_step = 0

        if st.button("🔍 Explore the Science Behind It"):
            st.session_state.show_science = True

        if st.session_state.show_science:
            st.markdown('### 🧬 Science Behind the Ritual')
            for s in R['science']:
                st.markdown(f'- {s}')

            st.markdown('---')
            st.markdown('### 🎯 Gen-Z Hook')
            st.write(R['genz'])
            st.radio('Your choice:', ['(choose one)', 'Option A', 'Option B', 'Option C'], index=0, key=f'hook_{ritual}')

            if st.button('🔊 Narrate This Story'):
                narrate(R['story'])

            st.markdown('---')
            if st.button("🧩 Ready to Test What You Learned?"):
                st.session_state.show_quiz = True
                st.session_state.quiz_step = 1

        if st.session_state.show_quiz:
            st.subheader('🧠 Quiz: Science × Culture')
            qna = [
                ('Which science idea explains trance in Theyyam?', ['Hydrodynamics','Sound entrainment','Photosynthesis'], 1),
                ('Why do snake boats have long hulls?', ['To increase drag','To reduce water resistance','Decoration only'], 1),
                ('What does the Vishukkani mirror symbolize?', ['Optics & positive priming','Magnetism','Refraction'], 0)
            ]
            qi = st.session_state.quiz_step - 1
            if qi < len(qna):
                q, opts, correct = qna[qi]
                ans = st.radio(f"{qi+1}. {q}", opts, index=None, key=f'q{qi}')
                if st.button("➡️ Next Question"):
                    if ans is not None:
                        if 'score' not in st.session_state: st.session_state.score = 0
                        if opts.index(ans) == correct: st.session_state.score += 1
                        st.session_state.quiz_step += 1
            else:
                sc = st.session_state.get('score', 0)
                st.markdown('---')
                st.success(f'Your Score: **{sc}/3**')
                if sc == 3:
                    st.balloons()
                    st.success('🎉 Perfect 3/3 — You’re a Science + Culture Pro!')
                elif sc == 2:
                    st.info('😎 2/3 — Great connection between belief and biology!')
                elif sc == 1:
                    st.warning('🧠 1/3 — You caught one! Explore more rituals to connect dots.')
                else:
                    st.error('😅 0/3 — Try again after revisiting Chechi’s stories.')

                if st.button("🔁 Restart Quiz"):
                    st.session_state.quiz_step = 1
                    st.session_state.score = 0

                # ---------- 💬 Ask Chechi ----------
                st.markdown('---')
                st.subheader("💬 Ask Chechi (Anveshaka Chatbot)")
                st.write("Got a question about this ritual, its science, or meaning? Ask me anything below 👇")

                user_q = st.text_input("Type your question here:", key=f"chat_{ritual}")
                if st.button("🔮 Get Answer", key=f"ask_{ritual}"):
                    answer = None
                    q_lower = user_q.lower()

                    local_sources = " ".join([
                        R['story'], R['history'], " ".join(R['science']), R['genz']
                    ]).lower()
                    if any(word in local_sources for word in q_lower.split()):
                        context = textwrap.shorten(R['story'], width=400, placeholder="...")
                        answer = f"🪔 Based on the ritual of {ritual}, here’s what I can tell you:\n\n{context}"

                    if not answer:
                        st.write("🔍 Fetching from trusted sources (NCERT / Tourism)...")
                        try:
                            search_url = f"https://www.google.com/search?q={ritual}+site:ncert.nic.in+OR+site:incredibleindia.gov.in"
                            answer = f"🌐 You can explore more here:\n👉 [View details]({search_url})"
                        except Exception as e:
                            answer = f"⚠️ Sorry, couldn’t fetch info right now ({e})."

                    st.success(answer)

else:
    st.info('✨ Select a ritual from the list above to begin your story with Chechi!')